### ISSUE TITLE
Regexy omijają pliki takie jak admin-functions.pho

### ISSUE THREAD

**Issue by gregxsunday** [JokerTux/szkolasecurity.pl-python-dla-bezpiecznikow#1]
https://github.com/JokerTux/szkolasecurity.pl-python-dla-bezpiecznikow/blob/086f1b395390973a577bf3242cf3e2e79255e276/2pracadom/2pracdom.py#L18

https://github.com/JokerTux/szkolasecurity.pl-python-dla-bezpiecznikow/blob/086f1b395390973a577bf3242cf3e2e79255e276/2pracadom/2pracdom.py#L19

Aktualne wyrażenia regularne łapią pliki, które mają słowa `admin` lub `user` zaraz przed rozszerzeniem.
Te regexy nie złapią takich linii jak:
```
wp-admin/admin-functions.php
wp-admin/admin-post.php
wp-admin/network/user-new.php
wp-admin/network/user-edit.php
```

Regex powinien wyglądać mnie więcej tak:
```
{/}{cokolwiek, oprócz /}{słowo admin lub słowo user}{cokolwiek, oprócz /}{rozszerzenie .php}{koniec linii}
```

**Comment by JokerTux** [comment]
Kurde na te chwile mam cos takiego  :
`{/}{[A-Za-z0-9_.]/}{admin}{[A-Za-z0-9_.]/}{.php$}` 
ale nie dziala ;)

**Comment by gregxsunday** [comment]
Chyba Cię wprowadziłem znakami `{}`. Nie powinno być w Twoim regexie.
Jedno z wielu rozwiązań wygląda tak:
```
/[^/]*(admin|user)[^/]*\.php$
```
Po kolei:
* `/` oznacza po prostu jeden slash
* `[^/]` oznacza dowolny znak oprócz slasha, a `*` oznacza 0 lub więcej
* `(admin|user)` oznacza słowo `admin` lub słowo `user`
* `[^/]` oznacza dowolny znak oprócz slasha, a `*` oznacza 0 lub więcej
* `\.` oznacza dosłowną kropkę (samo `.` oznaczałoby dowolny znak
* `php$` oznacza, że php musi być na końcu linii

Możesz użyć debuggex do wizualizacji:
https://www.debuggex.com/r/XONyKoPzYwZmanaF

**Comment by JokerTux** [comment]
O w morde . ale fajne ! Bede korzystal :)!!! 
Dziekuje Tobie jeszcze raz za pomoc a kod ju poprawilem. Nie zamykam narazie tego issue bo chce sie poduczyc troche regexow :). Poszukam jakis zadan w necie .

**Comment by JokerTux** [comment]
Jednego nie potrafie zrozumiec ,w Twoim przykladzie :
 `/[^/]*(admin|user)[^/]*\.php$` 
Pierwszy jest `/` - tutaj wszystko jasne.
Pozniej jest ` [^/] ` i tutaj rodzi sie moje pytanie czy jest on (regex) potrzebeny ? Jezeli jest potrzebny to moglbys mi przyblizyc dlaczego ? 

Odpalilem skrypt z takim kodem:
` /*(admin|user)[^/]*\.php$' `  i zwraca taki sam wynik jak Twoja wersja.

**Comment by gregxsunday** [comment]
Fakt, nie jest potrzebny. Moja logika była taka, że `/[^/]*` daje nam gwarancję, że jesteśmy po slashu, czyli w nazwie pliku, a nie w nazwie folderu. 
Natomiast to drugie `[^/]*` gwarantuje nam, że za słowem admin lub user nie będzie lub slasha, więc i tak na pewno będziemy w nazwie pliku.
Początkowy slash też można usunąć:
```
(admin|user)[^/]*\.php$
```

**Comment by JokerTux** [comment]
> Moja logika była taka, że /[^/]* daje nam gwarancję, że jesteśmy po slashu, czyli w nazwie pliku, a nie w nazwie folderu.

 To teraz juz wszystko jasne ;)!! Nie moglem wlasnie dojsc do czego on sluzy.Wydawalo mi sie ,ze mozna na Windowsie zrobic folder taki jak np " John/Johny " ale okazalo sie ze nie mozna :P

U mnie z kolei wyskakuje do excepta :
`except:
		print("oooops something went wrong...")`

Bez tego `/` w `*(admin|user)[^/]*\.php$' `

Za to dziala poprawnie w tej wersji :
`/*(admin|user)[^/]*\.php$'`

Jestem na Ubuntu i uzywam pythona3 3.8 moze to ma znaczenie :P ?
