### ISSUE TITLE
Uproszczenie printów

### ISSUE THREAD

**Issue by gregxsunday** [JokerTux/szkolasecurity.pl-python-dla-bezpiecznikow#2]
https://github.com/JokerTux/szkolasecurity.pl-python-dla-bezpiecznikow/blob/9bd4a7adf55807d91942b423cd9ab96f6d48ae87/2pracadom/2pracdom.py#L24-L28

Możesz uprościć to tak:
```py
if user or admin:
    print(path)
```

Jest to nie tylko ładniejsze i krótsze, ale też pozwoliłoby uniknąc duplikatów, w razie, gdyby w ffuf.log była linia:
```
wp-admin/admin-user.php
```
czy coś takiego. W obecnej formie taka linia byłaby wypisana dwa razy.

**Comment by JokerTux** [comment]
Dzieki bardzo ! Wlasnie sie zastanawialem jak to uproscic !
